<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function search_by_location($loc){
        $qb = $this->createQueryBuilder('j');
        if ($loc != null)
            $qb->andWhere("j.ville=:loc")->setParameter("loc", $loc);
        $query = $qb->getQuery();
        return $query->execute();
    }
}
